#pragma once

#define MODULE_DEBUG
#define MODULE_ROOTKIT
#define MODULE_FORMGRABBER
#define MODULE_BOTKILLER
#define MODULE_BACKCONNECT
#define MODULE_STEALERS
#define MODULE_POS_GRABBER
#define MODULE_KEYLOGGER